[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "b93af091cd3a0aa20e503b6f3dd0c30f3a09b76c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "ce8a3265f9008454c23cd6898e205757dd50cb8727147494a070b0d04832b8b0"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.4.0+0/CUDSS.v0.4.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "b05c9263bc0e149618a3b4b573d3eb490318f03d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "d91fe42d6881508e2729fa553fcb8c500f966c4963b2eecddfbcc5c55dc2fa42"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.4.0+0/CUDSS.v0.4.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "1231f841a7f913e1eb7fe8bc81667c245631adeb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "8b32d3e0bf68919183743bac0127c267d38097c73393b8b85b8ab33b5e044030"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.4.0+0/CUDSS.v0.4.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "4be52409fcd7f34654b0970ec2769e60ccfa6ea8"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "eae839405303e8b71256445000466875d84dbebe74a06bccc73c506a0996ec43"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.4.0+0/CUDSS.v0.4.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
