[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "3888e91c6bf08a4673b8cc32a5ceb0b910ea369b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "9b889c69352bd093ae91ee7a814fab4634d6603cfad2ef9abe584db93c74cce1"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "a4ab1ccb50e6055f941fea6abdf986f1962173fd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "8afa11cdfb25d15b929de447ebbb2206a08ffa97c85e4341237805c256079a8c"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "6d4bcf52ae069670908e5719b3574367ebcd76ac"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "da99e3dfb07cac6975f1e9888503160560829544193b3dfee06d40ef1309b213"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "55b621ccf0b684c44fccc694f644d731b55685cd"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "0623f333bf5089c2fe7091dc3bf345ee5a2826d3d19233e971f6fd351f5c61d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "803630e51d4afdc9d88be19eff4a30816029da79"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "5f573cfb29c97a4f39377951e20928bcf69e279051a7fd636ace698d8a7fcec3"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "0d73203628fe421e67481e294d290efdf39192a6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "7a7195053dfefb270c2255e6be6691406f24009d3848b84b7c27320050c3ee79"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "f5f78bc791c098da2ce723c7bbcb526183aeb7c5"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "76c78f06e239dedae872c45b0a8cf0c774ab29c4eeac1b22ee8fbd06851e9fca"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.7.1+0/CUDSS.v0.7.1.x86_64-w64-mingw32-cuda+13.0.tar.gz"
