[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d110d0d1ff3386623f23f1673ab3f753aa58a007"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "903803cfef020aa62a5495ddc9388bfc595167dd5141d6eb79909da891c1ab4a"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.5.0+0/CUDSS.v0.5.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "532810ec5cdb2429357f369687981791a5ae1f67"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "bd0a56d291ba4276f643e3ea0d7e51cc2d82bc8399b7958ddb738b3fc0a7782a"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.5.0+0/CUDSS.v0.5.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "5a29aa72b5248d1a80271d192433071c9a177d39"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "1cacf6407e7a65fbab2d230d98eba49969713e56143211e02c3f9a4fa2ca9f69"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.5.0+0/CUDSS.v0.5.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "aaea45b481c9eedb5bd3638c90a50e8b0d52da57"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "3f9f309c20bf2d04a7309349db13e152ac6d915f07f79f5d2ee53d4fcebf7525"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.5.0+0/CUDSS.v0.5.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
