[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "e8cad0180a8341d1c8a90a9637f85d0a3f0240f8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "d024c25ff7180d3e3741ac37682ebb651540545274b582acb58384aade3820de"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "c239332ee52c6e658ee03938ed7cc1a51e1b3a7b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "0b2fc76b699ac3fcc303d770f6f3dd7cf3d18f190c74168e68ae222abbf67cc9"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "cb837ef739706f9a53abd43b3ac062ae257fc496"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "54e5977a1e29a6742fae85ab9672d70c8d975e28b5fee675ce004c0251d1cc26"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "70f71e6957ad1d34eb5cd510ee7f1e8ea293bb37"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "45a71124d3f31fa3bc06b2ab1f85ad2f79882fa6f36b291353b4dbd36d1bfd48"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "0c7d8c403f078263e5664d2daaac814c2f8d26d4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "e864399b77f58234054bd35e29a6f3fa5f9c867ab36eb1a157b37a8a839deab6"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "79a0c602039025242be640588c7d9ca280d7cbed"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "31bd4de89cfe87a3eb303965e56ec4da0b772464e3147615671405d14ce5284b"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "10b495c15fc929e7c195c37eb8a312dc51646b54"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "2f571f8aa3ee350798d43d955a7401469601bc9c360651439cec247f74f3bded"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.8.0+0/CUDSS.v0.8.0.x86_64-w64-mingw32-cuda+13.0.tar.gz"
