[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "4e68029801a496e94561e7383b39ef605c0169cf"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "61909132713fa5f76c77e31ddef2809559f5b775409d2296a933a5745f394e03"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.2.1+0/CUDSS.v0.2.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "543b8f940d0b1d921e61e6189150b65200cdc932"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDSS.download]]
    sha256 = "4b7a6430da322411dbef2a08a4eae11ea4eac3238f607bbca7ba6816efd16c18"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.2.1+0/CUDSS.v0.2.1.aarch64-linux-gnu-cuda+12.0.tar.gz"
[[CUDSS]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "6aeee82e8e9b9e5545d4ba030fe444681ecd0570"
lazy = true
os = "windows"

    [[CUDSS.download]]
    sha256 = "44d7668d81264732372cca6fb52c413eadc6b0ec42230eacfdc006dd301b8067"
    url = "https://github.com/JuliaBinaryWrappers/CUDSS_jll.jl/releases/download/CUDSS-v0.2.1+0/CUDSS.v0.2.1.x86_64-w64-mingw32-cuda+12.0.tar.gz"
