# Autogenerated wrapper script for CUDSS_jll for aarch64-linux-gnu-cuda+13.0
export libcudss

using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("CUDSS")
JLLWrappers.@declare_library_product(libcudss, "libcudss.so.0")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libcudss,
        "lib/libcudss.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
