# Autogenerated wrapper script for CUDSS_jll for x86_64-linux-gnu-cuda+12.0
export libcudss

using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("CUDSS")
JLLWrappers.@declare_library_product(libcudss, "libcudss.so.0")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libcudss,
        "lib/libcudss.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
