# Autogenerated wrapper script for CUDSS_jll for x86_64-w64-mingw32-cuda+12.0
export libcudss

using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("CUDSS")
JLLWrappers.@declare_library_product(libcudss, "cudss64_0.dll")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libcudss,
        "bin\\cudss64_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
